### ISSUE TITLE
Old runtimes crash at HTMLCanvasElement type check

### ISSUE THREAD

**Issue by etpinard** [dfcreative/calc-sdf#2]
more precisely on this line:

https://github.com/dfcreative/bitmap-sdf/blob/master/index.js#L28

e.g. nw.js 0.12:

![image](https://user-images.githubusercontent.com/6675409/34626992-dd3a6d54-f22c-11e7-99f5-0c5d5a255cfc.png)

**Comment by dy** [comment]
Appreciate @etpinard! Fixed by https://github.com/dfcreative/bitmap-sdf/commit/815fda9610842b7b594b3ec78918e5ce587aa9f3
