### ISSUE TITLE
Assertion error in old runtime

### ISSUE THREAD

**Issue by etpinard** [dfcreative/calc-sdf#3]
e.g in nw.js

![image](https://user-images.githubusercontent.com/6675409/34630244-62ed9faa-f239-11e7-9a1b-c14c0050627d.png)

this is on line:

https://github.com/dfcreative/bitmap-sdf/blob/master/index.js#L64

**Comment by etpinard** [comment]
By the way @dfcreative you can try debugging nw.js using 

https://gist.github.com/etpinard/d27a44bd5dbee5490f20

if it helps. We're using nw.js 0.12: https://dl.nwjs.io/v0.12.0/

**Comment by etpinard** [comment]
@dfcreative can you address this **next**? Not being able to generate images in nw.js is probably the biggest blocker for the regl-based scattergl release.

**Comment by dy** [comment]
@etpinard should be fixed with https://github.com/dfcreative/bitmap-sdf/commit/0b8bb4f0a2bbc25bbc0d1bb1ce31d7d82765d718, the confusion is because of `Uint8ClampedArray` class - nwjs has both `global.Uint8ClampedArray` and `window.Uint8ClampedArray`. But now it hangs the nwjs on my machine, so please have a look, the problem seems to be out of this scope.

**Comment by etpinard** [comment]
Brilliant :sparkles: 

This appears to fix the other remaining nw.js [issue](https://plotly.slack.com/archives/D2797R800/p1515190399000518).

Looks like image tests are working for regl scattergl :tada: 

See the new baselines here: https://github.com/plotly/plotly.js/commit/c287efac745f7121b646868e17f00fe09d890fb7

You'll notice that some lines aren't very crisp:

![peek 2018-01-12 11-31](https://user-images.githubusercontent.com/6675409/34884897-2ebe2f9e-f78c-11e7-92ae-b689e25924ae.gif)

Is this expected? It seems to be a nw.js-only glitch. If so, we can ignore it as nw.js is on its deathbed.

**Comment by dy** [comment]
@etpinard yes, this is tricky antialiasing glitch, there do not seem to be regularities of when this uncrispiness appears, it seems to depend on specific canvas size.

**Comment by etpinard** [comment]
This appears fixed. Closing.
