### ISSUE TITLE
Missing License File

### ISSUE THREAD

**Issue by wcroteau** [dfcreative/calc-sdf#7]
There appears to be no proper license file in your repository nor in your npm package...

Please can you create this file and update your build/deploy process so that the file is included as a top-level file in the package?

This is important because your license (the MIT license) states:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

However you yourself don't include the license with that copy of the software.

This in turn makes it impossible for the consumers of your package to adhere to your license when using build automation tools.

Thanks!

**Comment by dy** [comment]
Done
