### ISSUE TITLE
readme example can't actually run

### ISSUE THREAD

**Issue by Pomax** [dfcreative/calc-sdf#8]
The readme example has the following loop:

```js
for (let i = 0; i < w; i++) {
	for (let j = 0; j < h; j++) {
		imgArr[j*w*4 + i*4 + 0] = arr[j*w+i]*255
		imgArr[j*w*4 + i*4 + 1] = arr[j*w+i]*255
		imgArr[j*w*4 + i*4 + 2] = arr[j*w+i]*255
		imgArr[j*w*4 + i*4 + 3] = 255
	}
}
```
but `arr` does not exist. Is this supposed to be `distances`?

It also starts with `requrie`, which should obviously be `require`.

**Comment by dy** [comment]
Yes, thanks, fixed

**Comment by Pomax** [comment]
(There's also the part where it relies on `document`, which doesn't exist on Node, so you may also need to rewrite that to use the `node-canvas` package instead of the web api, or not bother with canvas at all and show direct use of a Uin8Array or the like, which is probably better. Folks can figure out how to turn "whatever they're working with" into a typed array themselves)
